services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: zwitscher-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zwitscher-backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:5176
      ConnectionStrings__SqlDbConnection: "${DB_CONN}"
      JwtConfig__Secret: "${JWT_SECRET}"
    ports:
      - "5176:5176"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver:/var/opt/mssql
    
volumes:
  sqlserver:
