/* tslint:disable */
/* eslint-disable */
/**
 * Group7
 * An ASP.NET Core Web API for Group7
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ApplicationUser
 */
export interface ApplicationUser {
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'normalizedUserName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'normalizedEmail'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationUser
     */
    'emailConfirmed'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'passwordHash'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'securityStamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'concurrencyStamp'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'phoneNumber'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationUser
     */
    'phoneNumberConfirmed'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationUser
     */
    'twoFactorEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'lockoutEnd'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationUser
     */
    'lockoutEnabled'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ApplicationUser
     */
    'accessFailedCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof ApplicationUser
     */
    'role'?: Role;
    /**
     * 
     * @type {Gender}
     * @memberof ApplicationUser
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<Follower>}
     * @memberof ApplicationUser
     */
    'followers'?: Array<Follower> | null;
    /**
     * 
     * @type {Array<Following>}
     * @memberof ApplicationUser
     */
    'following'?: Array<Following> | null;
    /**
     * 
     * @type {Array<Post>}
     * @memberof ApplicationUser
     */
    'likedPosts'?: Array<Post> | null;
    /**
     * 
     * @type {Array<Post>}
     * @memberof ApplicationUser
     */
    'dislikedPosts'?: Array<Post> | null;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationUser
     */
    'bio'?: string | null;
    /**
     * 
     * @type {Array<Interest>}
     * @memberof ApplicationUser
     */
    'interests'?: Array<Interest> | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationUser
     */
    'locked'?: boolean;
    /**
     * 
     * @type {Array<Post>}
     * @memberof ApplicationUser
     */
    'posts'?: Array<Post> | null;
}


/**
 * 
 * @export
 * @interface Follower
 */
export interface Follower {
    /**
     * 
     * @type {number}
     * @memberof Follower
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Follower
     */
    'followerUserId'?: string | null;
    /**
     * 
     * @type {ApplicationUser}
     * @memberof Follower
     */
    'user'?: ApplicationUser;
}
/**
 * 
 * @export
 * @interface Following
 */
export interface Following {
    /**
     * 
     * @type {number}
     * @memberof Following
     */
    'id'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Following
     */
    'followingUserId'?: string | null;
    /**
     * 
     * @type {ApplicationUser}
     * @memberof Following
     */
    'user'?: ApplicationUser;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Gender = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;

export type Gender = typeof Gender[keyof typeof Gender];


/**
 * 
 * @export
 * @interface Interest
 */
export interface Interest {
    /**
     * 
     * @type {number}
     * @memberof Interest
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Interest
     */
    'name'?: string | null;
}
/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'userId'?: string | null;
    /**
     * 
     * @type {ApplicationUser}
     * @memberof Post
     */
    'user'?: ApplicationUser;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'firstname'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'lastName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'text'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    'upVotes'?: number;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    'downVotes'?: number;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'createdAt'?: string;
    /**
     * 
     * @type {Array<Post>}
     * @memberof Post
     */
    'comments'?: Array<Post> | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'dislikedByUserId'?: string | null;
    /**
     * 
     * @type {User}
     * @memberof Post
     */
    'dislikedByUser'?: User;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'likedByUserId'?: string | null;
    /**
     * 
     * @type {User}
     * @memberof Post
     */
    'likedByUser'?: User;
}
/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'title'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetails
     */
    'status'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'detail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'instance'?: string | null;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Role = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;

export type Role = typeof Role[keyof typeof Role];


/**
 * 
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof User
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<Follower>}
     * @memberof User
     */
    'followers'?: Array<Follower> | null;
    /**
     * 
     * @type {Array<Following>}
     * @memberof User
     */
    'following'?: Array<Following> | null;
    /**
     * 
     * @type {Array<Post>}
     * @memberof User
     */
    'likedPosts'?: Array<Post> | null;
    /**
     * 
     * @type {Array<Post>}
     * @memberof User
     */
    'dislikedPosts'?: Array<Post> | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'bio'?: string | null;
    /**
     * 
     * @type {Array<Interest>}
     * @memberof User
     */
    'interests'?: Array<Interest> | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'locked'?: boolean;
    /**
     * 
     * @type {Array<Post>}
     * @memberof User
     */
    'posts'?: Array<Post> | null;
}


/**
 * 
 * @export
 * @interface UserLoginRequestDto
 */
export interface UserLoginRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserLoginRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginRequestDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserRegistrationRequestDto
 */
export interface UserRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'password': string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationDBTestGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/DBTest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationLoginPost: async (userLoginRequestDto?: UserLoginRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRefreshTokenPost: async (tokenRequest?: TokenRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/RefreshToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRegisterPost: async (userRegistrationRequestDto?: UserRegistrationRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/Register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRegistrationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationDBTestGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationDBTestGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationLoginPost(userLoginRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationRefreshTokenPost(tokenRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationRegisterPost(userRegistrationRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationDBTestGet(options?: any): AxiosPromise<void> {
            return localVarFp.apiAuthenticationDBTestGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: any): AxiosPromise<void> {
            return localVarFp.apiAuthenticationLoginPost(userLoginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: any): AxiosPromise<void> {
            return localVarFp.apiAuthenticationRefreshTokenPost(tokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: any): AxiosPromise<void> {
            return localVarFp.apiAuthenticationRegisterPost(userRegistrationRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationDBTestGet(options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationDBTestGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logs in a user.
     * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationLoginPost(userLoginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refreshes the access token.
     * @param {TokenRequest} [tokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationRefreshTokenPost(tokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Registers a new user.
     * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationRegisterPost(userRegistrationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGetByUsernameUsernameGet: async (username: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('apiUserGetByUsernameUsernameGet', 'username', username)
            const localVarPath = `/api/User/GetByUsername/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdDelete', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdGet', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {ApplicationUser} [applicationUser] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPut: async (id: string, applicationUser?: ApplicationUser, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdPut', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(applicationUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {ApplicationUser} [applicationUser] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost: async (applicationUser?: ApplicationUser, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(applicationUser, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ApplicationUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserGetByUsernameUsernameGet(username: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserGetByUsernameUsernameGet(username, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {ApplicationUser} [applicationUser] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdPut(id: string, applicationUser?: ApplicationUser, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdPut(id, applicationUser, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {ApplicationUser} [applicationUser] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserPost(applicationUser?: ApplicationUser, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApplicationUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserPost(applicationUser, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet(options?: any): AxiosPromise<Array<ApplicationUser>> {
            return localVarFp.apiUserGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGetByUsernameUsernameGet(username: string, options?: any): AxiosPromise<ApplicationUser> {
            return localVarFp.apiUserGetByUsernameUsernameGet(username, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiUserIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet(id: string, options?: any): AxiosPromise<ApplicationUser> {
            return localVarFp.apiUserIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {ApplicationUser} [applicationUser] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPut(id: string, applicationUser?: ApplicationUser, options?: any): AxiosPromise<ApplicationUser> {
            return localVarFp.apiUserIdPut(id, applicationUser, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {ApplicationUser} [applicationUser] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost(applicationUser?: ApplicationUser, options?: any): AxiosPromise<ApplicationUser> {
            return localVarFp.apiUserPost(applicationUser, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Gets a list of all users.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserGet(options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a user with the username.
     * @param {string} username The username of the user to get.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserGetByUsernameUsernameGet(username: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserGetByUsernameUsernameGet(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a user with the specified ID.
     * @param {string} id The ID of the user to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdDelete(id: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a user with the specified ID.
     * @param {string} id The ID of the user to get.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdGet(id: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an existing user.
     * @param {string} id The ID of the user to update.
     * @param {ApplicationUser} [applicationUser] The updated user information.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdPut(id: string, applicationUser?: ApplicationUser, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdPut(id, applicationUser, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new user.
     * @param {ApplicationUser} [applicationUser] The user to create.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserPost(applicationUser?: ApplicationUser, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserPost(applicationUser, options).then((request) => request(this.axios, this.basePath));
    }
}


