/* tslint:disable */
/* eslint-disable */
/**
 * Group7
 * An ASP.NET Core Web API for Group7
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface AuthResult
 */
export interface AuthResult {
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof AuthResult
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'email'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof AuthResult
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    'followers'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    'following'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    'likedPosts'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    'dislikedPosts'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'bio'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof AuthResult
     */
    'interests'?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthResult
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'refreshToken'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthResult
     */
    'token'?: string | null;
}


/**
 * 
 * @export
 * @enum {string}
 */

export const Gender = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;

export type Gender = typeof Gender[keyof typeof Gender];


/**
 * 
 * @export
 * @interface Post
 */
export interface Post {
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'userId'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'text'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    'upVotes'?: number;
    /**
     * 
     * @type {number}
     * @memberof Post
     */
    'downVotes'?: number;
    /**
     * 
     * @type {string}
     * @memberof Post
     */
    'date'?: string;
    /**
     * 
     * @type {Array<Post>}
     * @memberof Post
     */
    'comments'?: Array<Post> | null;
}
/**
 * 
 * @export
 * @interface ProblemDetails
 */
export interface ProblemDetails {
    [key: string]: any;

    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'type'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'title'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProblemDetails
     */
    'status'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'detail'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProblemDetails
     */
    'instance'?: string | null;
}
/**
 * 
 * @export
 * @enum {string}
 */

export const Role = {
    NUMBER_0: 0,
    NUMBER_1: 1,
    NUMBER_2: 2
} as const;

export type Role = typeof Role[keyof typeof Role];


/**
 * 
 * @export
 * @interface TokenRequest
 */
export interface TokenRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof TokenRequest
     */
    'refreshToken': string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof User
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'followers'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'following'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'likedPosts'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'dislikedPosts'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'bio'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof User
     */
    'interests'?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'locked'?: boolean;
}


/**
 * 
 * @export
 * @interface UserAdd
 */
export interface UserAdd {
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof UserAdd
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'email'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof UserAdd
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'password'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'bio'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAdd
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserAdd
     */
    'interests'?: Array<string> | null;
}


/**
 * 
 * @export
 * @interface UserEdit
 */
export interface UserEdit {
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'avatar'?: string | null;
    /**
     * 
     * @type {Role}
     * @memberof UserEdit
     */
    'role'?: Role;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'username'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'email'?: string | null;
    /**
     * 
     * @type {Gender}
     * @memberof UserEdit
     */
    'gender'?: Gender;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'birthDate'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEdit
     */
    'followers'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEdit
     */
    'following'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEdit
     */
    'likedPosts'?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEdit
     */
    'dislikedPosts'?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'bio'?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserEdit
     */
    'interests'?: Array<string> | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserEdit
     */
    'locked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserEdit
     */
    'password'?: string | null;
}


/**
 * 
 * @export
 * @interface UserLoginRequestDto
 */
export interface UserLoginRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserLoginRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginRequestDto
     */
    'password': string;
}
/**
 * 
 * @export
 * @interface UserRegistrationRequestDto
 */
export interface UserRegistrationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistrationRequestDto
     */
    'password': string;
}

/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationLoginPost: async (userLoginRequestDto?: UserLoginRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userLoginRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRefreshTokenPost: async (tokenRequest?: TokenRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/RefreshToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRegisterPost: async (userRegistrationRequestDto?: UserRegistrationRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authentication/Register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userRegistrationRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationLoginPost(userLoginRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationRefreshTokenPost(tokenRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthenticationRegisterPost(userRegistrationRequestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @summary Logs in a user.
         * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: any): AxiosPromise<AuthResult> {
            return localVarFp.apiAuthenticationLoginPost(userLoginRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refreshes the access token.
         * @param {TokenRequest} [tokenRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: any): AxiosPromise<void> {
            return localVarFp.apiAuthenticationRefreshTokenPost(tokenRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Registers a new user.
         * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: any): AxiosPromise<AuthResult> {
            return localVarFp.apiAuthenticationRegisterPost(userRegistrationRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @summary Logs in a user.
     * @param {UserLoginRequestDto} [userLoginRequestDto] The user login request data transfer object (DTO).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationLoginPost(userLoginRequestDto?: UserLoginRequestDto, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationLoginPost(userLoginRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refreshes the access token.
     * @param {TokenRequest} [tokenRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationRefreshTokenPost(tokenRequest?: TokenRequest, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationRefreshTokenPost(tokenRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Registers a new user.
     * @param {UserRegistrationRequestDto} [userRegistrationRequestDto] The user registration request data transfer object (DTO).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public apiAuthenticationRegisterPost(userRegistrationRequestDto?: UserRegistrationRequestDto, options?: AxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthenticationRegisterPost(userRegistrationRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * PostApi - axios parameter creator
 * @export
 */
export const PostApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets a list of all posts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Post`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a post by its ID.
         * @param {string} id The ID of the post.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiPostIdGet', 'id', id)
            const localVarPath = `/api/Post/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new post.
         * @param {Post} [post] The post to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostPost: async (post?: Post, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Post`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(post, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostApi - functional programming interface
 * @export
 */
export const PostApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all posts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPostGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Post>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPostGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a post by its ID.
         * @param {string} id The ID of the post.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPostIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Post>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPostIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Creates a new post.
         * @param {Post} [post] The post to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPostPost(post?: Post, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Post>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiPostPost(post, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PostApi - factory interface
 * @export
 */
export const PostApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all posts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostGet(options?: any): AxiosPromise<Array<Post>> {
            return localVarFp.apiPostGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a post by its ID.
         * @param {string} id The ID of the post.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostIdGet(id: string, options?: any): AxiosPromise<Post> {
            return localVarFp.apiPostIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new post.
         * @param {Post} [post] The post to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPostPost(post?: Post, options?: any): AxiosPromise<Post> {
            return localVarFp.apiPostPost(post, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PostApi - object-oriented interface
 * @export
 * @class PostApi
 * @extends {BaseAPI}
 */
export class PostApi extends BaseAPI {
    /**
     * 
     * @summary Gets a list of all posts.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public apiPostGet(options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).apiPostGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a post by its ID.
     * @param {string} id The ID of the post.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public apiPostIdGet(id: string, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).apiPostIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new post.
     * @param {Post} [post] The post to create.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostApi
     */
    public apiPostPost(post?: Post, options?: AxiosRequestConfig) {
        return PostApiFp(this.configuration).apiPostPost(post, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGetByUsernameUsernameGet: async (username: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('apiUserGetByUsernameUsernameGet', 'username', username)
            const localVarPath = `/api/User/GetByUsername/{username}`
                .replace(`{${"username"}}`, encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdDelete', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdGet', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {UserEdit} [userEdit] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPut: async (id: string, userEdit?: UserEdit, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdPut', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userEdit, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {UserAdd} [userAdd] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost: async (userAdd?: UserAdd, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userAdd, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<User>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserGetByUsernameUsernameGet(username: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserGetByUsernameUsernameGet(username, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {UserEdit} [userEdit] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdPut(id: string, userEdit?: UserEdit, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdPut(id, userEdit, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {UserAdd} [userAdd] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserPost(userAdd?: UserAdd, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserPost(userAdd, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets a list of all users.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet(options?: any): AxiosPromise<Array<User>> {
            return localVarFp.apiUserGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a user with the username.
         * @param {string} username The username of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGetByUsernameUsernameGet(username: string, options?: any): AxiosPromise<User> {
            return localVarFp.apiUserGetByUsernameUsernameGet(username, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a user with the specified ID.
         * @param {string} id The ID of the user to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete(id: string, options?: any): AxiosPromise<void> {
            return localVarFp.apiUserIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a user with the specified ID.
         * @param {string} id The ID of the user to get.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet(id: string, options?: any): AxiosPromise<User> {
            return localVarFp.apiUserIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an existing user.
         * @param {string} id The ID of the user to update.
         * @param {UserEdit} [userEdit] The updated user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPut(id: string, userEdit?: UserEdit, options?: any): AxiosPromise<User> {
            return localVarFp.apiUserIdPut(id, userEdit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new user.
         * @param {UserAdd} [userAdd] The user to create.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost(userAdd?: UserAdd, options?: any): AxiosPromise<User> {
            return localVarFp.apiUserPost(userAdd, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Gets a list of all users.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserGet(options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a user with the username.
     * @param {string} username The username of the user to get.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserGetByUsernameUsernameGet(username: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserGetByUsernameUsernameGet(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a user with the specified ID.
     * @param {string} id The ID of the user to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdDelete(id: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a user with the specified ID.
     * @param {string} id The ID of the user to get.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdGet(id: string, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an existing user.
     * @param {string} id The ID of the user to update.
     * @param {UserEdit} [userEdit] The updated user information.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserIdPut(id: string, userEdit?: UserEdit, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdPut(id, userEdit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new user.
     * @param {UserAdd} [userAdd] The user to create.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public apiUserPost(userAdd?: UserAdd, options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserPost(userAdd, options).then((request) => request(this.axios, this.basePath));
    }
}


