import { AuthUser, Post, User } from "@/interfaces";

export const userData: AuthUser = {
  id: 0,
  token:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  firstName: "Admin",
  lastName: "Nimda",
  role: "Admin",
  username: "ANimda",
  email: "admin@nimda.de",
  password: "Admin1!",
  avatar:
    "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
  follower: [1, 2],
  following: [1, 2],
  liked: [],
  disliked: [],
  bio: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ex illum ad? Tenetur dolore accusantium laborum amet doloribus dignissimos reiciendis eveniet, exercitationem dicta perferendis, ullam cupiditate. Quidem sed non nulla!",
  createdAt: new Date(),
  birthdate: new Date(),
  gender: "männlich",
  interests: ["Schach", "Bücher", "Fußball"],
  refreshToken:
    "jfklasjfklajslfjklasjdfjasdkljfklsdjfkljsdlafjlkasdjfkljasdlfjasdklfjasdljflsdj",
};

export const users: User[] = [
  {
    id: 0,
    firstName: "Admin",
    lastName: "Nimda",
    role: "Admin",
    username: "ANimda",
    email: "admin@nimda.de",
    avatar:
      "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
    follower: [1, 2],
    following: [1, 2],
    liked: [],
    disliked: [],
    bio: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere ex illum ad? Tenetur dolore accusantium laborum amet doloribus dignissimos reiciendis eveniet, exercitationem dicta perferendis, ullam cupiditate. Quidem sed non nulla!",
    createdAt: new Date(),
    gender: "männlich",
    birthdate: new Date(),
    interests: ["Schach", "Bücher", "Fußball"],
  },
  {
    id: 1,
    username: "JDoe",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "Admin",
    follower: [2, 0],
    following: [2, 0],
    liked: [],
    disliked: [],
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    bio: "Hallo das ist meine Bio.",
    createdAt: new Date(),
  },
  {
    id: 2,
    username: "JaneDoe",
    firstName: "Jane",
    lastName: "Doe",
    email: "jane.doe@example.com",
    role: "Moderator",
    follower: [1, 0],
    following: [1, 0],
    liked: [],
    disliked: [],
    avatar: "https://avatars0.githubusercontent.com/u/9064066?v=4&s=460",
    bio: "Hallo das ist meine Bio.",
    createdAt: new Date(),
    birthdate: new Date(),
  },
];

export const allPosts: Post[] = [
  {
    id: 1,
    userId: 0,
    firstName: "Admin",
    lastName: "Nimda",
    username: "ANimda",
    avatar:
      "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-05-1"),
    comments: [],
    files: [],
  },
  {
    id: 2,
    userId: 0,
    firstName: "Admin",
    lastName: "Nimda",
    username: "ANimda",
    avatar:
      "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-05-02T18:56:00"),
    comments: [],
    files: [],
  },
  {
    id: 3,
    userId: 2,
    firstName: "Jane",
    lastName: "Doe",
    username: "JaneDoe",
    avatar: "https://avatars0.githubusercontent.com/u/9064066?v=4&s=460",
    upvotes: 15,
    downvotes: 10,
    text: "I'm planning a road trip across the US this summer. Any recommendations?",
    date: new Date("2022-04-11"),
    comments: [],
    files: [],
  },
  {
    id: 4,
    userId: 1,
    firstName: "John",
    lastName: "Doe",
    username: "JDoe",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-04-27"),
    comments: [],
    files: [],
  },
];

export const userPosts: Post[] = [
  {
    id: 1,
    userId: 0,
    firstName: "Admin",
    lastName: "Nimda",
    username: "ANimda",
    avatar:
      "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-05-1"),
    comments: [],
    files: [],
  },
  {
    id: 2,
    userId: 0,
    firstName: "Admin",
    lastName: "Nimda",
    username: "ANimda",
    avatar:
      "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-05-02T18:56:00"),
    comments: [],
    files: [],
  },
];

export const followedUsersPosts: Post[] = [
  {
    id: 3,
    userId: 2,
    firstName: "Jane",
    lastName: "Doe",
    username: "JaneDoe",
    avatar: "https://avatars0.githubusercontent.com/u/9064066?v=4&s=460",
    upvotes: 15,
    downvotes: 10,
    text: "I'm planning a road trip across the US this summer. Any recommendations?",
    date: new Date("2022-04-11"),
    comments: [],
    files: [],
  },
  {
    id: 4,
    userId: 1,
    firstName: "John",
    lastName: "Doe",
    username: "JDoe",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
    date: new Date("2023-04-27"),
    comments: [],
    files: [],
  },
];
