import { AuthUser, Post, User } from "@/interfaces";

export const userData: AuthUser = {
  firstName: "Admin",
  lastName: "Nimda",
  token:
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
  id: 0,
  role: "Admin",
  username: "AdminN",
  email: "admin@nimda.de",
  password: "Admin1!",
  avatar:
    "https://cdn.pixabay.com/photo/2020/06/24/19/12/cabbage-5337431_1280.jpg",
};

export const users: User[] = [
  {
    id: 1,
    username: "user1",
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    role: "Admin",
    password: "789das789dfas789dfs",
  },
  {
    id: 2,
    username: "user2",
    firstName: "Jane",
    lastName: "Doe",
    email: "jane.doe@example.com",
    role: "Moderator",
    password: "789das789dfas789dfs",
  },
  {
    id: 3,
    username: "user3",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@example.com",
    role: "Nutzer",
    password: "789das789dfas789dfs",
  },
  {
    id: 4,
    username: "user4",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    role: "Nutzer",
    password: "789das789dfas789dfs",
  },
];

export const allPosts: Post[] = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Smith",
    username: "ASmith",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 20,
    downvotes: 5,
    text: "Just finished reading a great book about astrophysics. Highly recommend it!",
  },
  {
    id: 2,
    firstName: "John",
    lastName: "Doe",
    username: "JDoe",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 15,
    downvotes: 10,
    text: "I'm planning a road trip across the US this summer. Any recommendations?",
  },
  {
    id: 3,
    firstName: "Emily",
    lastName: "Johnson",
    username: "EJohnson",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 7,
    downvotes: 2,
    text: "Just tried a new Thai restaurant and it was amazing!",
  },
  {
    id: 4,
    firstName: "Mike",
    lastName: "Brown",
    username: "MBrown",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 12,
    downvotes: 8,
    text: "I can't believe how much snow we've gotten this winter!",
  },
  {
    id: 5,
    firstName: "Sarah",
    lastName: "Lee",
    username: "SLee",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 25,
    downvotes: 3,
    text: "Just finished a 10k race and it was tough but so worth it!",
  },
  {
    id: 6,
    firstName: "David",
    lastName: "Nguyen",
    username: "DNguyen",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 8,
    downvotes: 12,
    text: "I'm learning how to cook and it's been a lot of fun so far!",
  },
  {
    id: 7,
    firstName: "Jessica",
    lastName: "Park",
    username: "JPark",
    avatar: "https://cdn.vuetifyjs.com/images/john.jpg",
    upvotes: 18,
    downvotes: 6,
    text: "Just got back from a trip to Japan and it was amazing!",
  },
];
